---- MODULE NFQuorum_xstate ----
(*
 * .planning/formal/tla/NFQuorum_xstate.tla
 * GENERATED by bin/xstate-to-tla.cjs
 * Source: src/machines/nf-workflow.machine.ts
 * Regenerate: node bin/xstate-to-tla.cjs src/machines/nf-workflow.machine.ts --config=.planning/formal/tla/guards/nf-workflow.json --module=NFQuorum
 * Generated: 2026-03-13
 *
 * XState machine id: nf-workflow
 * Initial state:     IDLE
 * States (4):          IDLE, COLLECTING_VOTES, DELIBERATING, DECIDED
 * Final states:      DECIDED
*)
EXTENDS Naturals, FiniteSets, TLC

\* ── Variables ────────────────────────────────────────────────────────────────
VARIABLES
    state,  \* FSM state
    slotsAvailable,  \* default: 0  annotation: event
    successCount,  \* default: 0  annotation: event
    deliberationRounds,  \* default: 0  annotation: deliberationRounds + 1
    maxDeliberation,  \* default: 9  annotation: const
    maxSize,  \* default: 3  annotation: (no annotation)
    polledCount  \* default: 0  annotation: (no annotation)

vars == <<state, slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Type invariant ────────────────────────────────────────────────────────────
\* @requirement QUORUM-01
TypeOK ==
    /\ state \in {"IDLE", "COLLECTING_VOTES", "DELIBERATING", "DECIDED"}
    /\ slotsAvailable \in Nat  \* FIXME: tighten bound if needed
    /\ successCount \in Nat  \* FIXME: tighten bound if needed
    /\ deliberationRounds \in Nat  \* FIXME: tighten bound if needed
    /\ maxDeliberation \in Nat  \* FIXME: tighten bound if needed
    /\ maxSize \in Nat  \* FIXME: tighten bound if needed
    /\ polledCount \in Nat  \* FIXME: tighten bound if needed

\* ── Initial state ─────────────────────────────────────────────────────────────
Init ==
    /\ state = "IDLE"
    /\ slotsAvailable = 0
    /\ successCount = 0
    /\ deliberationRounds = 0
    /\ maxDeliberation = 9
    /\ maxSize = 3
    /\ polledCount = 0

\* ── Actions ────────────────────────────────────────────────────────────────────

\* IDLE -[QUORUM_START]-> COLLECTING_VOTES
IdleQuorumStart(slotsAvailable) ==
    /\ state = "IDLE"
    /\ state' = "COLLECTING_VOTES"
    /\ slotsAvailable' = slotsAvailable  \* param from event
    /\ polledCount' = polledCount  \* FIXME: XState assign for polledCount
    /\ UNCHANGED <<successCount, deliberationRounds, maxDeliberation, maxSize>>

\* IDLE -[CIRCUIT_BREAK]-> IDLE
IdleCircuitBreak ==
    /\ state = "IDLE"
    /\ state' = "IDLE"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* IDLE -[DECIDE]-> IDLE
IdleDecide ==
    /\ state = "IDLE"
    /\ state' = "IDLE"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* IDLE -[VOTES_COLLECTED]-> IDLE
IdleVotesCollected ==
    /\ state = "IDLE"
    /\ state' = "IDLE"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[VOTES_COLLECTED / unanimityMet]-> DECIDED
CollectingVotesVotesCollectedToDECIDED(successCount) ==
    /\ state = "COLLECTING_VOTES"
    /\ successCount = polledCount
    /\ state' = "DECIDED"
    /\ successCount' = successCount  \* param from event
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[VOTES_COLLECTED]-> DELIBERATING
CollectingVotesVotesCollectedToDELIBERATING(successCount) ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "DELIBERATING"
    /\ successCount' = successCount  \* param from event
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[QUORUM_START]-> COLLECTING_VOTES
CollectingVotesQuorumStart ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "COLLECTING_VOTES"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[CIRCUIT_BREAK]-> COLLECTING_VOTES
CollectingVotesCircuitBreak ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "COLLECTING_VOTES"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[DECIDE]-> COLLECTING_VOTES
CollectingVotesDecide ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "COLLECTING_VOTES"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / unanimityMet]-> DECIDED
DeliberatingVotesCollectedToDECIDED(successCount) ==
    /\ state = "DELIBERATING"
    /\ successCount = polledCount
    /\ state' = "DECIDED"
    /\ successCount' = successCount  \* param from event
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / noInfiniteDeliberation]-> DELIBERATING
DeliberatingVotesCollectedToDELIBERATING ==
    /\ state = "DELIBERATING"
    /\ deliberationRounds < MaxDeliberation
    /\ state' = "DELIBERATING"
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, successCount, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED]-> DECIDED
DeliberatingVotesCollectedToDECIDED ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[DECIDE]-> DECIDED
DeliberatingDecide ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[QUORUM_START]-> DELIBERATING
DeliberatingQuorumStart ==
    /\ state = "DELIBERATING"
    /\ state' = "DELIBERATING"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[CIRCUIT_BREAK]-> DELIBERATING
DeliberatingCircuitBreak ==
    /\ state = "DELIBERATING"
    /\ state' = "DELIBERATING"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED is a final (absorbing) state
StayDECIDED ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Next ──────────────────────────────────────────────────────────────────────
Next ==
    \/ \E slotsAvailable \in Nat : IdleQuorumStart(slotsAvailable)
    \/ IdleCircuitBreak
    \/ IdleDecide
    \/ IdleVotesCollected
    \/ \E successCount \in Nat : CollectingVotesVotesCollectedToDECIDED(successCount)
    \/ \E successCount \in Nat : CollectingVotesVotesCollectedToDELIBERATING(successCount)
    \/ CollectingVotesQuorumStart
    \/ CollectingVotesCircuitBreak
    \/ CollectingVotesDecide
    \/ \E successCount \in Nat : DeliberatingVotesCollectedToDECIDED(successCount)
    \/ DeliberatingVotesCollectedToDELIBERATING
    \/ DeliberatingVotesCollectedToDECIDED
    \/ DeliberatingDecide
    \/ DeliberatingQuorumStart
    \/ DeliberatingCircuitBreak
    \/ DecidedDecide
    \/ DecidedCircuitBreak
    \/ DecidedQuorumStart
    \/ DecidedVotesCollected
    \/ StayDECIDED

\* ── Specification ─────────────────────────────────────────────────────────────
Spec == Init /\ [][Next]_vars
        /\ WF_vars(IdleQuorumStart)
        /\ WF_vars(IdleCircuitBreak)
        /\ WF_vars(IdleDecide)
        /\ WF_vars(IdleVotesCollected)
        /\ WF_vars(CollectingVotesVotesCollectedToDECIDED)
        /\ WF_vars(CollectingVotesVotesCollectedToDELIBERATING)
        /\ WF_vars(CollectingVotesQuorumStart)
        /\ WF_vars(CollectingVotesCircuitBreak)
        /\ WF_vars(CollectingVotesDecide)
        /\ WF_vars(DeliberatingVotesCollectedToDECIDED)
        /\ WF_vars(DeliberatingVotesCollectedToDELIBERATING)
        /\ WF_vars(DeliberatingDecide)
        /\ WF_vars(DeliberatingQuorumStart)
        /\ WF_vars(DeliberatingCircuitBreak)
        /\ WF_vars(DecidedDecide)
        /\ WF_vars(DecidedCircuitBreak)
        /\ WF_vars(DecidedQuorumStart)
        /\ WF_vars(DecidedVotesCollected)
        /\ WF_vars(StayDECIDED)

\* ── Invariants (add domain-specific properties here) ──────────────────────────
\* TypeOK is the structural baseline. Add semantic invariants below.

====
