---- MODULE NFQuorum_xstate ----
(*
 * .planning/formal/tla/NFQuorum_xstate.tla
 * GENERATED by bin/xstate-to-tla.cjs (hand-fixed: 24 semantic errors)
 * Source: src/machines/nf-workflow.machine.ts
 * Regenerate: node bin/xstate-to-tla.cjs src/machines/nf-workflow.machine.ts --config=.planning/formal/tla/guards/nf-workflow.json --module=NFQuorum
 * Generated: 2026-03-14
 *
 * XState machine id: nf-workflow
 * Initial state:     IDLE
 * States (4):          IDLE, COLLECTING_VOTES, DELIBERATING, DECIDED
 * Final states:      DECIDED
 *
 * Hand-fix summary (4 bug categories):
 *   1. Variable shadowing: renamed \E bound vars to sa/sc to avoid shadowing VARIABLES
 *   2. Duplicate operator: merged two DeliberatingVotesCollectedToDECIDED into one
 *      parameterized operator with guard-based disjunction
 *   3. Missing DECIDED-state operators: added DecidedDecide, DecidedCircuitBreak,
 *      DecidedQuorumStart, DecidedVotesCollected as self-loops
 *   4. Case mismatch: MaxDeliberation -> maxDeliberation
 *)
EXTENDS Naturals, FiniteSets, TLC

\* ── Constants (model-checking bounds) ────────────────────────────────────────
CONSTANTS MaxSlots,      \* upper bound for slotsAvailable event values
          MaxSuccessCnt  \* upper bound for successCount event values

\* ── Variables ────────────────────────────────────────────────────────────────
VARIABLES
    state,  \* FSM state
    slotsAvailable,  \* default: 0  annotation: event
    successCount,  \* default: 0  annotation: event
    deliberationRounds,  \* default: 0  annotation: deliberationRounds + 1
    maxDeliberation,  \* default: 9  annotation: const
    maxSize,  \* default: 3  annotation: (no annotation)
    polledCount  \* default: 0  annotation: (no annotation)

vars == <<state, slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Type invariant ────────────────────────────────────────────────────────────
\* @requirement QUORUM-01
TypeOK ==
    /\ state \in {"IDLE", "COLLECTING_VOTES", "DELIBERATING", "DECIDED"}
    /\ slotsAvailable \in Nat  \* FIXME: tighten bound if needed
    /\ successCount \in Nat  \* FIXME: tighten bound if needed
    /\ deliberationRounds \in Nat  \* FIXME: tighten bound if needed
    /\ maxDeliberation \in Nat  \* FIXME: tighten bound if needed
    /\ maxSize \in Nat  \* FIXME: tighten bound if needed
    /\ polledCount \in Nat  \* FIXME: tighten bound if needed

\* ── Initial state ─────────────────────────────────────────────────────────────
Init ==
    /\ state = "IDLE"
    /\ slotsAvailable = 0
    /\ successCount = 0
    /\ deliberationRounds = 0
    /\ maxDeliberation = 9
    /\ maxSize = 3
    /\ polledCount = 0

\* ── Actions ────────────────────────────────────────────────────────────────────

\* IDLE -[QUORUM_START]-> COLLECTING_VOTES
\* Fix #1: renamed param from slotsAvailable -> sa to avoid shadowing VARIABLE
IdleQuorumStart(sa) ==
    /\ state = "IDLE"
    /\ state' = "COLLECTING_VOTES"
    /\ slotsAvailable' = sa  \* param from event
    /\ polledCount' = polledCount  \* FIXME: XState assign for polledCount
    /\ UNCHANGED <<successCount, deliberationRounds, maxDeliberation, maxSize>>

\* IDLE -[CIRCUIT_BREAK]-> IDLE
IdleCircuitBreak ==
    /\ state = "IDLE"
    /\ state' = "IDLE"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* IDLE -[DECIDE]-> IDLE
IdleDecide ==
    /\ state = "IDLE"
    /\ state' = "IDLE"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* IDLE -[VOTES_COLLECTED]-> IDLE
IdleVotesCollected ==
    /\ state = "IDLE"
    /\ state' = "IDLE"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[VOTES_COLLECTED / unanimityMet]-> DECIDED
\* Fix #1: renamed param from successCount -> sc
CollectingVotesVotesCollectedToDECIDED(sc) ==
    /\ state = "COLLECTING_VOTES"
    /\ sc = polledCount
    /\ state' = "DECIDED"
    /\ successCount' = sc  \* param from event
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[VOTES_COLLECTED]-> DELIBERATING
\* Fix #1: renamed param from successCount -> sc
CollectingVotesVotesCollectedToDELIBERATING(sc) ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "DELIBERATING"
    /\ successCount' = sc  \* param from event
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[QUORUM_START]-> COLLECTING_VOTES
CollectingVotesQuorumStart ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "COLLECTING_VOTES"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[CIRCUIT_BREAK]-> COLLECTING_VOTES
CollectingVotesCircuitBreak ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "COLLECTING_VOTES"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[DECIDE]-> COLLECTING_VOTES
CollectingVotesDecide ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "COLLECTING_VOTES"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / unanimityMet]-> DECIDED
\* Fix #1: renamed param from successCount -> sc
\* Fix #2: merged with the duplicate parameterless version (line 128 in original)
\*         The parameterless version was a fallback (no guard) -> DECIDED.
\*         Now this single operator handles both: with unanimity guard (sc = polledCount)
\*         and the fallback path is DeliberatingVotesCollectedFallbackToDECIDED below.
DeliberatingVotesCollectedToDECIDED(sc) ==
    /\ state = "DELIBERATING"
    /\ sc = polledCount
    /\ state' = "DECIDED"
    /\ successCount' = sc  \* param from event
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED]-> DECIDED (fallback, no guard)
\* Fix #2: renamed from duplicate DeliberatingVotesCollectedToDECIDED
DeliberatingVotesCollectedFallbackToDECIDED ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / noInfiniteDeliberation]-> DELIBERATING
\* Fix #4: MaxDeliberation -> maxDeliberation (case-sensitive)
DeliberatingVotesCollectedToDELIBERATING ==
    /\ state = "DELIBERATING"
    /\ deliberationRounds < maxDeliberation
    /\ state' = "DELIBERATING"
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, successCount, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[DECIDE]-> DECIDED
DeliberatingDecide ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[QUORUM_START]-> DELIBERATING
DeliberatingQuorumStart ==
    /\ state = "DELIBERATING"
    /\ state' = "DELIBERATING"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[CIRCUIT_BREAK]-> DELIBERATING
DeliberatingCircuitBreak ==
    /\ state = "DELIBERATING"
    /\ state' = "DELIBERATING"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── DECIDED state self-loops ────────────────────────────────────────────────
\* Fix #3: added missing operators referenced in Next

\* DECIDED -[DECIDE]-> DECIDED (self-loop in final state)
DecidedDecide ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED -[CIRCUIT_BREAK]-> DECIDED (self-loop in final state)
DecidedCircuitBreak ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED -[QUORUM_START]-> DECIDED (self-loop in final state)
DecidedQuorumStart ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED -[VOTES_COLLECTED]-> DECIDED (self-loop in final state)
DecidedVotesCollected ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED is a final (absorbing) state — catch-all
StayDECIDED ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Next ──────────────────────────────────────────────────────────────────────
\* Fix #1: \E bound vars renamed to sa/sc to avoid shadowing module VARIABLES
\* Fix #2: line 170 now references DeliberatingVotesCollectedFallbackToDECIDED
Next ==
    \/ \E sa \in 0..MaxSlots : IdleQuorumStart(sa)
    \/ IdleCircuitBreak
    \/ IdleDecide
    \/ IdleVotesCollected
    \/ \E sc \in 0..MaxSuccessCnt : CollectingVotesVotesCollectedToDECIDED(sc)
    \/ \E sc \in 0..MaxSuccessCnt : CollectingVotesVotesCollectedToDELIBERATING(sc)
    \/ CollectingVotesQuorumStart
    \/ CollectingVotesCircuitBreak
    \/ CollectingVotesDecide
    \/ \E sc \in 0..MaxSuccessCnt : DeliberatingVotesCollectedToDECIDED(sc)
    \/ DeliberatingVotesCollectedToDELIBERATING
    \/ DeliberatingVotesCollectedFallbackToDECIDED
    \/ DeliberatingDecide
    \/ DeliberatingQuorumStart
    \/ DeliberatingCircuitBreak
    \/ DecidedDecide
    \/ DecidedCircuitBreak
    \/ DecidedQuorumStart
    \/ DecidedVotesCollected
    \/ StayDECIDED

\* ── Specification ─────────────────────────────────────────────────────────────
Spec == Init /\ [][Next]_vars

\* ── Invariants (add domain-specific properties here) ──────────────────────────
\* TypeOK is the structural baseline. Add semantic invariants below.

====
