-- formal/alloy/build-test-quality.als
-- Generated by close-formal-gaps (batch mode)
-- Build and test quality — hooks/dist rebuild, npm test, MCP server porting
--
-- Requirements:
--   BLD-01: hooks/dist rebuilt from current source
--   BLD-02: npm test passes with 0 failures
--   STD-02: Gen1 MCP repos ported to Gen2 per-tool architecture
--
-- @requirement BLD-01
-- @requirement BLD-02
-- @requirement STD-02

module build_test_quality

-- A requirement that must be satisfied
abstract sig Requirement {}
one sig BLD_01 extends Requirement {}
one sig BLD_02 extends Requirement {}
one sig STD_02 extends Requirement {}

-- SystemState tracks which requirements are satisfied
sig SystemState {
    satisfied: set Requirement
}

-- All requirements must be satisfiable in at least one state
fact AllSatisfiable {
    some s: SystemState | Requirement in s.satisfied
}

-- Monotonicity: once satisfied, a requirement stays satisfied
-- (models the invariant that shipped features are not removed)
pred Monotonic [pre, post: SystemState] {
    pre.satisfied in post.satisfied
}

-- @requirement BLD-01
assert BLD_01_Covered {
    all s: SystemState | BLD_01 in s.satisfied
}

-- @requirement BLD-02
assert BLD_02_Covered {
    all s: SystemState | BLD_02 in s.satisfied
}

-- @requirement STD-02
assert STD_02_Covered {
    all s: SystemState | STD_02 in s.satisfied
}

-- Verify all requirements can be simultaneously satisfied
assert AllSimultaneous {
    some s: SystemState | Requirement in s.satisfied
}

check BLD_01_Covered for 3 SystemState, 5 Requirement
check BLD_02_Covered for 3 SystemState, 5 Requirement
check STD_02_Covered for 3 SystemState, 5 Requirement
check AllSimultaneous for 3 SystemState, 5 Requirement

run { some s: SystemState | Requirement in s.satisfied } for 3 SystemState, 5 Requirement
