-- formal/alloy/subagent-orchestration.als
-- Generated by close-formal-gaps (batch mode)
-- Subagent orchestration — context retrieval, phase accumulation, retrieval agents
--
-- Requirements:
--   ORCH-01: context-retriever.cjs fetches domain-relevant artifacts
--   ORCH-02: context-stack.cjs maintains JSONL phase index
--   ORCH-03: Quorum dispatch enriches prompts with context
--
-- @requirement ORCH-01
-- @requirement ORCH-02
-- @requirement ORCH-03

module subagent_orchestration

-- A requirement that must be satisfied
abstract sig Requirement {}
one sig ORCH_01 extends Requirement {}
one sig ORCH_02 extends Requirement {}
one sig ORCH_03 extends Requirement {}

-- SystemState tracks which requirements are satisfied
sig SystemState {
    satisfied: set Requirement
}

-- All requirements must be satisfiable in at least one state
fact AllSatisfiable {
    some s: SystemState | Requirement in s.satisfied
}

-- Monotonicity: once satisfied, a requirement stays satisfied
-- (models the invariant that shipped features are not removed)
pred Monotonic [pre, post: SystemState] {
    pre.satisfied in post.satisfied
}

-- @requirement ORCH-01
assert ORCH_01_Covered {
    all s: SystemState | ORCH_01 in s.satisfied
}

-- @requirement ORCH-02
assert ORCH_02_Covered {
    all s: SystemState | ORCH_02 in s.satisfied
}

-- @requirement ORCH-03
assert ORCH_03_Covered {
    all s: SystemState | ORCH_03 in s.satisfied
}

-- Verify all requirements can be simultaneously satisfied
assert AllSimultaneous {
    some s: SystemState | Requirement in s.satisfied
}

check ORCH_01_Covered for 3 SystemState, 5 Requirement
check ORCH_02_Covered for 3 SystemState, 5 Requirement
check ORCH_03_Covered for 3 SystemState, 5 Requirement
check AllSimultaneous for 3 SystemState, 5 Requirement

run { some s: SystemState | Requirement in s.satisfied } for 3 SystemState, 5 Requirement
