-- formal/alloy/vhs-ci-hardening.als
-- Generated by close-formal-gaps (batch mode)
-- VHS tape CI reliability — shell hardening
--
-- Requirements:
--   VIS-02: VHS tape hardened for CI (zsh, PATH export, CLAUDECODE unset)
--
-- @requirement VIS-02

module vhs_ci_hardening

-- A requirement that must be satisfied
abstract sig Requirement {}
one sig VIS_02 extends Requirement {}

-- SystemState tracks which requirements are satisfied
sig SystemState {
    satisfied: set Requirement
}

-- All requirements must be satisfiable in at least one state
fact AllSatisfiable {
    some s: SystemState | Requirement in s.satisfied
}

-- Monotonicity: once satisfied, a requirement stays satisfied
-- (models the invariant that shipped features are not removed)
pred Monotonic [pre, post: SystemState] {
    pre.satisfied in post.satisfied
}

-- @requirement VIS-02
assert VIS_02_Covered {
    all s: SystemState | VIS_02 in s.satisfied
}

-- Verify all requirements can be simultaneously satisfied
assert AllSimultaneous {
    some s: SystemState | Requirement in s.satisfied
}

check VIS_02_Covered for 3 SystemState, 3 Requirement
check AllSimultaneous for 3 SystemState, 3 Requirement

run { some s: SystemState | Requirement in s.satisfied } for 3 SystemState, 3 Requirement
